# Generated by Django 3.2.7 on 2021-10-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='news',
        ),
        migrations.AddField(
            model_name='author',
            name='blog',
            field=models.TextField(default=' '),
        ),
    ]
